### ISSUE TITLE
i think you forgot CURL denpedencie ;)

### ISSUE THREAD

**Issue by willemijns** [SoftCreatR/imei#19]
Sorry my logs disappears but you forget for

Building jpegxl 
to check if curl is installed or not ;)

I see on script you displays "Used web client : curl" so i think you forced curl somewhere on "Building jpegxl" step.

**Comment by SoftCreatR** [comment]
Hi,

IMEI itself supports `curl`, `wget` and even `httpie` to perform external connections. However, JPEG XL ships with a script `deps.sh` that installs additional dependencies. Though this isn't the recommended way to install them, it's IMHO the most reliable, because if the requirements ever change, these changes will be automatically covered without the need to manually check their requirements after every release. Long story short: The curl requirement comes from an external script. But I'll either add `curl` to the list of dependencies to install, or use the recommended way to install the dependencies.

**Comment by willemijns** [comment]
if curl is not installed, we can not compile.period.

I do not understand "use the recommended way to install the additional dependencies." 

you create a script to easily compiles a software, you need to adapt so you can check at startup if you want 

if
not exist /usr/bin/curl 
and 
https://github.com/ImageMagick/jpeg-xl/blob/main/deps.sh contains 'curl -L "
then
...............
fi

*BUT* 99% of your users are interested to compile with no pain ;)

In your case, because you know JPEG XL sources can ask to use external software for any reason. you need to consider than
download and check the raw content of "deps.sh file" needs to be done during the first step of your script ;)

**Comment by SoftCreatR** [comment]
This has already been fixed in the latest development build.
