### ISSUE TITLE
build-dir does not work

### ISSUE THREAD

**Issue by trajano** [SoftCreatR/imei#22]
## 📚 Documentation

documentation says build-dir is where things would get built, setting it to `/work` makes it appear to use it, but all the files are still going to /usr/local in the end.

## Have you spent some time to check if this issue has been raised before?

(Have you googled for a similar issue or checked our older issues for a similar bug)

### Have you read the [Code of Conduct](https://github.com/SoftCreatR/imei/blob/main/CODE_OF_CONDUCT.md)?

[x] I have read the Code of Conduct

**Comment by trajano** [comment]
Looking through the code it appears you're using but but the `make install` will install to `/usr/local` regardless.  I think there may be a parameter that needs to be set in the configure.

**Comment by SoftCreatR** [comment]
IM should now be built in the given directory. However, building the additional libs at another location is somewhat difficult.

**Comment by trajano** [comment]
Hmm I got the following after getting the latest changes

```
 Installing dependencies       [OK]     [..]
 Building aom                  [OK]     [..]
 Building libheif              [SKIPPED (aom is required but not installed)]
```

**Comment by SoftCreatR** [comment]
The problem here is, that aom for example can't be built in a different directory, because of `cmake`. `configure` on the other hand allows it. I've changed the logic in version 6.1.1 slightly, so $BUILD_DIR only defines the directory where ImageMagick will be built. Libs will still be built in the default directories (which is `/usr/local`).
