### ISSUE TITLE
Not HEIC support

### ISSUE THREAD

**Issue by nightdread** [SoftCreatR/imei#79]
The script completely works, but after installing it, there is still no support for HEIC.

 Detected OS     : Ubuntu 20.04.6 LTS
 Detected Arch   : aarch64
 Detected Cores  : 8

Version: ImageMagick 7.1.1-10 Q16-HDRI aarch64 3b5d98645:20230520 https://imagemagick.org
Copyright: (C) 1999 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules OpenMP(4.5) 
Delegates (built-in): bzlib cairo djvu fftw fontconfig freetype jbig jng jpeg jxl lcms lqr ltdl lzma openexr pangocairo png rsvg tiff webp wmf x xml zlib
Compiler: gcc (9.4)

**Comment by SoftCreatR** [comment]
Can you provide the imei.log file?

**Comment by nightdread** [comment]
[imei.log](https://github.com/SoftCreatR/imei/files/11581403/imei.log)

**Comment by SoftCreatR** [comment]
I have to admit, that IMEI was never tested on AArch64 / ARM64. Maybe, libheif isn't compatible with this architecture.

I will test this by myself, and get back to you.

**Comment by SoftCreatR** [comment]
There were two problems:

1. The package libdav1d-dev doesn't exist in Ubuntu 20.04. This leads to a failure of the dependency installation. Since it's not really required, I just removed it from the dependencies.
2. The source package list, that is added during the execution, wasn't compatible with AArch64 due do the fact, that at least on Ubuntu, a different URL is used.

**Comment by nightdread** [comment]
php -r 'phpinfo();' | grep HEIC
php: symbol lookup error: /usr/local/lib/ImageMagick-7.1.1/modules-Q16HDRI/coders/heic.so: undefined symbol: heif_init

**Comment by SoftCreatR** [comment]
Please create a new issue for that.
